
spring:
  datasource:
    driver:
      class: com.mysql.cj.jdbc.Driver
#    url: 'jdbc:mysql://sql12.freesqldatabase.com:3306/sql12607345'
#    username: sql12607345
#    password: etjyKtf4Ys
    url: 'jdbc:mysql://localhost:3306/DBtest'
    username: kienpt
    password: 12345
server:
  port: 8082
jwt:
  privateKeyPath: cert/rice_service_private.key
  passphrase: abcd1234