
spring:
  datasource:
    driver:
      class: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://sql12.freesqldatabase.com:3306/sql12610463'
    username: sql12610463
    password: EJ5zjR6mLP

    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: 100
      minimum-idle: 1
      connectionTimeout: 30000 #30s
      idleTimeout: 600000 #10 minutes
      maxLifetime: 1800000 #30 minutes
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
server:
  port: 8082
jwt:
  privateKeyPath: cert/rice_service_private.key
  passphrase: abcd1234